language: java
sudo: false
jdk:
  - oraclejdk8
branches:
  only:
    - master
    - dev
cache:
  directories:
    - ".autoconf"
    - "$HOME/.m2"
script: mvn clean verify  -Dmaven.test.redirectTestOutputToFile=true

after_success:
  - bash <(curl -s https://codecov.io/bash)
